{{- if .Values.globalService }}
apiVersion: assist.eu/v1
kind: MultiClusterService
metadata:
  name: {{ include "api.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  ports:
    - name: api
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: {{ .Values.api.service.protocol }}
    - name: api2
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: {{ .Values.api.service.protocol }}
{{- end }}