kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.persistentVolume.name | quote }}
  labels:
    {{- include "smartorchestrator.selectorLabels" . | nindent 8 }}
spec:
  accessModes:
    - {{ .Values.persistentVolume.accessMode | quote }}
  capacity:
    storage: {{ .Values.persistentVolume.storage | quote }}
  hostPath:
    path: {{ .Values.persistentVolume.path | quote }}
  storageClassName:  {{ .Values.persistentVolume.storageClassName | quote }}
