kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: assist-api
  namespace: default
subjects:
  - kind: ServiceAccount
    name: assist-api
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: assist-api

