kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: assist-api
rules:
  - apiGroups:
      - ""
      - "apps"
      - "batch"
    resources:
      - endpoints
      - deployments
      - pods
      - jobs
      - pods/log
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection