# Default values for enabler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# String to partially override enabler.fullname template (will maintain the release name)
nameOverride: ""
# String to fully override enabler.fullname template
fullnameOverride: ""
# Deploy all the components in the same node
enablerNodeSelector: {}

# Component api values
api:
  tier: external
  image:
    repository: ravaga/vpn-enabler
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  replicaCount: 1

  apiSvc:
    type: NodePort
    nodePort: ""
    port: 3000
    targetPort: 3000
    # this value will also be used for the container's API_PORT env var
    containerPort: 3000
    protocol: TCP

  wireguardSvc:
    type: NodePort
    nodePort: ""
    port: 51820
    targetPort: 51820
    # this value will also be used for the container's WG_PORT env var
    containerPort: 51820
    protocol: UDP

  # The specification of the resources is needed for the proper functioning 
  # of the Smart Orchestrator enabler (requests)
  # and of the Resource provisioning enabler (limits)
  resources:
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: false

  podSecurityContext: {}
  securityContext: {}

  # Configure the usage of an external database (not deployed using this chart)
  externalDatabase:
    enabled: false
    host: vpn-db
    port: 27017
    username: user
    password: p4ssw0rd

  # Include here the environment variables to be used in the component's manifest (container section).
  # Here and in the manifest is included an example.
  envVars:
    wgPrivateKey: "qAuVUEbmcI3ofLsjJmQ6+RtEejoNX+WHs7QOsIccn0Y="
    serverIP: "192.168.1.1"
    wgSubnet: "192.168.2.1/24"
    peerAllowedIPs: "0.0.0.0/0,::/0"

  imagePullSecrets: []
  nodeSelector: {}
  tolerations: []
  affinity: {}

# Component db values
db:
  tier: internal
  image:
    repository: mongo
    pullPolicy: IfNotPresent
    tag: "4.4.13"

  replicaCount: 1
  service:
    type: ClusterIP
    nodePort: ""
    port: 27017
    targetPort: 27017
    containerPort: 27017
    protocol: TCP

  # The specification of the resources is needed for the proper functioning 
  # of the Smart Orchestrator enabler (requests)
  # and of the Resource provisioning enabler (limits)
  resources:
    requests:
      cpu: 100m
      memory: 256Mi

  autoscaling:
    enabled: false

  podSecurityContext: {}
  securityContext: {}

  # Include here the environment variables to be used in the component's manifest (container section).
  # Here and in the manifest is included an example.
  envVars:
    username: user
    password: p4ssw0rd

  persistence:
    accessModes:
      - ReadWriteOnce
    size: 50Mi

  imagePullSecrets: []
  nodeSelector: {}
  tolerations: []
  affinity: {}

