apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-db-network-policy
spec:
  podSelector:
    matchLabels:
      enabler: {{ .Release.Name }}
      tier: db
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              enabler: {{ .Release.Name }}
              tier: api
      ports:
        - protocol: TCP
          port: {{ .Values.mongoDbPort }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              enabler: {{ .Release.Name }}
              tier: api
