apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo
  labels:
    enabler: {{ .Release.Name }}
    tier: db
spec:
  selector:
    enabler: {{ .Release.Name }}
    tier: db
  ports:
    - port: {{ .Values.mongoDbPort }}