apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-api-network-policy
spec:
  podSelector:
    matchLabels:
      enabler: {{ .Release.Name }}
      tier: api
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: {{ .Values.wgApiPort }}
        - protocol: UDP
          port: {{ .Values.wireguardPort }}
