apiVersion: v1
kind: Service
metadata:
  name: wireguard-api
spec:
  type: {{ .Values.wgApiSvcType }}
  selector:
    enabler: {{ .Release.Name }}
    tier: api
  ports:
    - port: {{ .Values.wgApiPort }}
      nodePort: {{ .Values.wgApiNodePort }}
      name: api
      targetPort: {{ .Values.wgApiPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: wireguard
spec:
  type: {{ .Values.wgSvcType }}
  selector:
    enabler: {{ .Release.Name }}
    tier: api
  ports:
    - port: {{ .Values.wireguardPort }}
      nodePort: {{ .Values.wireguardNodePort }}
      protocol: UDP
      targetPort: {{ .Values.wireguardPort }}