apiVersion: v1
kind: Service
metadata:
  name: {{ include "elastic.svc.headless" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "elastic.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.elastic.service.port }}
      targetPort: {{ .Values.elastic.service.targetPort }}
      protocol: {{ .Values.elastic.service.protocol }}
  selector:
    {{- include "elastic.selectorLabels" . | nindent 4 }}