apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.name" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.api.name }}
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.apiSvc.containerPort }}
              protocol: {{ .Values.api.apiSvc.protocol }}
            - containerPort: {{ .Values.api.wireguardSvc.containerPort }}
              protocol: {{ .Values.api.wireguardSvc.protocol }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          {{- with .Values.api.envVars }}
          env:
            - name: API_PORT
              value: {{ .wgApiPort | quote }}
            - name: SERVER_IP
              value: {{ .serverIP }}
            - name: WG_PRIVATE_KEY
              value: {{ .wgPrivateKey }}
            - name: WG_SUBNET
              value: {{ .wgSubnet }}
            - name: WG_PORT
              value: {{ .wireguardPort | quote }}
            - name: PEER_ALLOWED_IPS
              value: {{ .peerAllowedIPs }}
            - name: MONGODB_HOST
              value: {{ .mongoDbHost }}
            - name: MONGODB_PORT
              value: {{ .mongoDbPort | quote }}
            - name: MONGODB_USER
              value: {{ .mongoDbUser }}
            - name: MONGODB_PASS
              value: {{ .mongoDbPass }}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
            privileged: true
          {{- end }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
