apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.name" . }}-api
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.apiSvc.type }}
  ports:
    - port: {{ .Values.api.apiSvc.port }}
      targetPort: {{ .Values.api.apiSvc.targetPort }}
      protocol: {{ .Values.api.apiSvc.protocol }}
      {{- if and (or (eq .Values.api.apiSvc.type "NodePort") (eq .Values.api.apiSvc.type "LoadBalancer")) (not (empty .Values.api.apiSvc.nodePort)) }}
      nodePort: {{ .Values.api.apiSvc.nodePort }}
      {{ end }}
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}
