apiVersion: v1
kind: Service
metadata:
  name: osm-api
spec:
  type: NodePort #NodePort
  selector:
    type: osm
    tier: api
  ports:
    - port: 5001
      nodePort: 5001
      name: api
      targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osm-api
spec:
  replicas: 1
  selector:
    matchLabels:
      type: osm
      tier: api
  template:
    metadata:
      labels:
        type: osm
        tier: api
    spec:
      serviceAccountName: assist-api
      containers:
        - name: osm-api
          image: fmbiot/osm-api:1.2.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          env:
            - name: DB_CNN
              value: "mongodb://osm-mongo/enablersdb"
            - name: OSM_HOST
              value: "nbi.osm"
            - name: OSM_PORT
              value: "9999"
            - name: PORT
              value: "5001"
          volumeMounts:
            - name: task-pv-storage
              mountPath: /etc/targets/
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
            privileged: true
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: pv-claim-api
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-api
  labels:
    type: local
spec:
  storageClassName: api
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-api
spec:
  storageClassName: api
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: assist-api
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: assist-api
rules:
  - apiGroups:
      - ""
      - "apps"
      - "batch"
    resources:
      - endpoints
      - deployments
      - pods
      - jobs
      - pods/log
    verbs:
      - get
      - list
      - watch
      - create
      - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: assist-api
  namespace: default
subjects:
  - kind: ServiceAccount
    name: assist-api
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: assist-api


