# Default values for enabler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# String to partially override enabler.fullname template (will maintain the release name)
nameOverride: ""
# String to fully override enabler.fullname template
fullnameOverride: ""
# Deploy all the components in the same node
enablerNodeSelector: {}

# Cilium Multi-cluster global service
globalService: false

# Component api values
api:
  tier: external
  image:
    repository: ravaga/ltse-api
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  replicaCount: 1
  service:
    type: NodePort
    nodePort: ""
    port: 8080
    targetPort: 8080
    containerPort: 8080
    protocol: TCP

  # The specification of the resources is needed for the proper functioning 
  # of the Smart Orchestrator enabler (requests)
  # and of the Resource provisioning enabler (limits)
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  podSecurityContext: {}
  securityContext: {}

  # Include here the environment variables to be used in the component's manifest (container section).
  envVars: {}

  imagePullSecrets: []
  nodeSelector: {}
  tolerations: []
  affinity: {}

# Component elastic values
elastic:
  tier: internal
  image:
    repository: elasticsearch
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "7.16.3"

  replicaCount: 1

  service:
    type: ClusterIP
    nodePort: ""
    port: 9200
    targetPort: 9200
    containerPort: 9200
    protocol: TCP

  service2:
    type: ClusterIP
    nodePort: ""
    port: 9300
    targetPort: 9300
    containerPort: 9300
    protocol: TCP

  # The specification of the resources is needed for the proper functioning 
  # of the Smart Orchestrator enabler (requests)
  # and of the Resource provisioning enabler (limits)
  resources:
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    requests:
      cpu: 300m
      memory: 8Gi

  autoscaling:
    enabled: false

  podSecurityContext: {}
  securityContext: {}

  # Include here the environment variables to be used in the component's manifest (container section).
  # Here and in the manifest is included an example.
  envVars:
    discoveryType: single-node
    nodeName: ltse

  persistence:
    accessModes:
      - ReadWriteOnce
    size: 1Gi

  imagePullSecrets: []
  nodeSelector: {}
  tolerations: []
  affinity: {}

# Component postgrest values
postgrest:
  tier: internal
  image:
    repository: postgrest
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v9.0.0"

  replicaCount: 1
  service:
    type: ClusterIP
    nodePort: ""
    port: 3000
    targetPort: 3000
    containerPort: 3000
    protocol: TCP

  # The specification of the resources is needed for the proper functioning 
  # of the Smart Orchestrator enabler (requests)
  # and of the Resource provisioning enabler (limits)
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  podSecurityContext: {}
  securityContext: {}

  # Include here the environment variables to be used in the component's manifest (container section).
  # Here and in the manifest is included an example.
  envVars:
    # pgrstDbUri: postgres://postgres:4ss1st10t@ltse-postgres/assist
    pgrstDBSchema: public
    pgrstDbAnonRole: postgres

  imagePullSecrets: []
  nodeSelector: {}
  tolerations: []
  affinity: {}

# Component postgresql values
postgresql:
  tier: internal
  image:
    repository: postgres
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  replicaCount: 1
  service:
    type: ClusterIP
    nodePort: ""
    port: 5432
    targetPort: 5432
    containerPort: 5432
    protocol: TCP

  # The specification of the resources is needed for the proper functioning 
  # of the Smart Orchestrator enabler (requests)
  # and of the Resource provisioning enabler (limits)
  resources:
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    requests:
      cpu: 200m
      memory: 2Gi

  autoscaling:
    enabled: false

  podSecurityContext: {}
  securityContext: {}

  # Include here the environment variables to be used in the component's manifest (container section).
  envVars:
    postgresUser: postgres
    postgresPassword: 4ss1st10t
    postgresDb: assist

  persistence:
    accessModes:
      - ReadWriteOnce
    size: 500Mi

  imagePullSecrets: []
  nodeSelector: {}
  tolerations: []
  affinity: {}

