apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.svc.headless" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: {{ .Values.postgresql.service.targetPort }}
      protocol: {{ .Values.postgresql.service.protocol }}
  selector:
    {{- include "postgresql.selectorLabels" . | nindent 4 }}